### ISSUE TITLE
No Hardware SPI on SAMD21 Xplained Pro

### ISSUE THREAD

**Issue by StephiB** [adafruit/Adafruit_BME680#10]
Hi, unfortunatly hardware SPI is not working with BME680 on SAMD21 Xplained Pro board. Wiith BME280 it works on all 3 SPI interfaces perfectly. 

`
#include <SPI.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME680.h>

#define BME_SCK SCK
#define BME_MISO MISO
#define BME_MOSI MOSI
#define BME_CS SS

#define SEALEVELPRESSURE_HPA (1013.25)

Adafruit_BME680 bme(BME_CS); // hardware SPI no funktion!
//Adafruit_BME680 bme(BME_CS, BME_MOSI, BME_MISO,  BME_SCK); // is working
`

this is what i get with  #define BME680_DEBUG and Hardware SPI:

`SPI $F3 => 0x1, 
	SPI $60 <= 0xB6, 
	SPI $F3 => 0x1, 
	SPI $D0 => 0x38, 
Result: -3
Could not find a valid BME680 sensor, check wiring!`

**Comment by ladyada** [comment]
figured it out :)
