### ISSUE TITLE
warning: left shift count >= width of type

### ISSUE THREAD

**Issue by voxspox** [adafruit/Adafruit_BME680#12]
Adafruit_BME680: v1.0.5
Arduino IDE: 1.8.5
Arduino Uno Board

I get the following warning:

    .../Arduino/libraries/Adafruit_BME680_Library/bme680.c: In function 'calc_pressure':
    .../Arduino/libraries/Adafruit_BME680_Library/bme680.c:864:2: warning: left shift count >= width of type
    var4 = (1 << 31);

**Comment by ladyada** [comment]
possibly fixed in the recent update to latest API! i dont see it...please re-open if you see this again :)

**Comment by voxspox** [comment]
ok, I will keep an eye on this :)
