### ISSUE TITLE
Compile error for esp8266 arduino delay function pointer

### ISSUE THREAD

**Issue by janzieg** [adafruit/Adafruit_BME680#2]
The begin() function causes a compile error right now when compiling with esp8266 arduino:

> Adafruit_BME680.cpp:89:23: error: invalid conversion from 'void (*)(long unsigned int)' to 'bme680_delay_fptr_t {aka void (*)(unsigned int)}' [-fpermissive]

as standard delay function is not compatible with expected signature from _bme680_defs.h_.

A wrapper function is required:

```
// Our hardware interface functions
...
static void delay_msec(uint32_t ms);
...

bool Adafruit_BME680::begin(uint8_t addr) {
    ...
    gas_sensor.delay_ms = &delay_msec;
    ...
}
...
static void delay_msec(uint32_t ms){
  delay(ms);
}
```

This fixed the compilation error for me.

**Comment by ladyada** [comment]
thx!
