### ISSUE TITLE
How to use the Adafruit library for Shuttle board

### ISSUE THREAD

**Issue by Maitreyee2095** [adafruit/Adafruit_BME680#20]
I am trying to integrate bme680 with Arduino uno, I am using BOSCH SHUTTLE BOARD, the BOSCH libraries do not support UNO wanted to use Adafruit Library instead. Is there anyway i can do so?

**Comment by ladyada** [comment]
should work, but you'll want to contact the vendor of the shuttle board for support on how to wire it!
