### ISSUE TITLE
Random "Adafruit_sensor" include

### ISSUE THREAD

**Issue by timcharper** [adafruit/Adafruit_BME680#25]
Adafruit_BME680.h has this line:

```
#include <Adafruit_Sensor.h>
```

It cannot compile because there is no such file defined.

**Comment by ladyada** [comment]
in https://github.com/adafruit/Adafruit_BME680/blob/master/README.md

**Comment by timcharper** [comment]
Doh!

But why is this even there? I just comment out the include and it compiles fine.
