### ISSUE TITLE
BME680 gas resistance to ppm

### ISSUE THREAD

**Issue by pswin** [adafruit/Adafruit_BME680#27]
How can I convert BME680's gas resistance to ppm? Is there any ready to use a method in the library? 

What I want is to measure Air quality.

**Comment by ladyada** [comment]
there is not

**Comment by kazimyuksel** [comment]
perfect customer support...

**Comment by Pythonaire** [comment]
https://jayconsystems.com/blog/understanding-a-gas-sensor
maybe you can adopt this.
