### ISSUE TITLE
BM680 wrong temprature

### ISSUE THREAD

**Issue by pswin** [adafruit/Adafruit_BME680#28]
I have 3 sensors for measuring temperature:

- DHT11
- DS1820
- BME680

while the two other sensors return the temperature around 21*C, BME680 returns 23.5*C. I know the two other sensors are not very stable but at least their value is almost near to each other. This 2-degree gap between the values makes me worry. In my use-case (the device that I need to create), such an error is not acceptable.

I have found many complains about BME680 on the internet that it does not return accurate temperature and humidity values. Is it a software error? Or BME680 is not accurate. or completely vice versa BME680 is accurate and the gap stems from an error in the other two sensors?

How can I get a reliable temperature value? (does BME680 need calibration?)

**Comment by dhalbert** [comment]
Could you bring this up in the support forums? https://forums.adafruit.com. This is more for issues with driver.

There has been some discussion about the BME680 accuracy in the forums, and there are more people familiar with the sensor there. For example: https://forums.adafruit.com/viewtopic.php?f=19&t=128198.

Re calibration: https://learn.adafruit.com/calibrating-sensors/why-calibrate

The BME680 is supposedly accurate to +/- 1.0C. Consider whether you need the other features of the BME680, or could you use a temperature-only device.
