### ISSUE TITLE
Feedback: Test on custom board.

### ISSUE THREAD

**Issue by hecko** [adafruit/Adafruit_BME680#3]
I can confirm this code working with BME680 bought from Mouser on a custom board with ATMEGA328P without external crystal using I2C. Arduino IDE 1.8.3

The only value Im not sure this library correctly outputs is the gas value. The datasheet says this should be a value between 0-500 and the library outputs in my case values like 23219

**Comment by G6EJD** [comment]
The 0-500 range is the output of the Bosch IAQ algorithm (external library) not the so-called gas resistance which I notice Adafruit has converted to Kohms now with a divide /1000. My sensor typically outputs in the range 50000-5000000 or 50K-500K. You can make your own IAQ, I used 0-25% humidity plus 0-75% gas then scaled that to 0-500. There is no IAQ standard afaik.

**Comment by ladyada** [comment]
that is correct, the IAQ algorithm they use is under lock & key, and only available in precompiled library formatl. @G6EJD where'd you get the idea for the hum+gas mix? i found some readings i put here https://learn.adafruit.com/adafruit-bme680-humidity-temperature-barometic-pressure-voc-gas/downloads which may be useful

**Comment by G6EJD** [comment]
Many organisations use the 0-500 IAQ index, but no one says how it’s comprised, so I figured an environment is affected by humidity (very low is not good, 40% is perfect or very high is not good) and then for gas a nominal reading with no obvious gas around is good, I chose the range 50K is very bad and 500K very good combined and scaled the results to 100% then as an add-on scaled it to the de-facto IAQ. The code is in github G6EJD.

**Comment by janzieg** [comment]
These guys managed the integrationof the Bosch BSEC library that does all the calculations: https://github.com/DFRobot/DFRobot_BME680.
Would be nice to have this within here.

(Main point: BSEC is precompiled and platform specific).

**Comment by ESP32DE** [comment]
hi @ladyada 
thanks for the lib. 
i checked the BOSCH Driver SRC and [did a small PR ](https://github.com/BoschSensortec/BME680_driver/pull/16) on https://github.com/BoschSensortec/BME680_driver

i [did try your lib today](https://twitter.com/eMbeddedHome/status/959146544388820993) on [Olimex ESP32Pro Board](https://esp32.com/viewtopic.php?f=17&t=2227#p10519) and my output looks like this:
![grafik](https://user-images.githubusercontent.com/16070445/35699602-db2ae95c-0790-11e8-8c6b-e12f9f8c557c.png)

it work's

now comes fine tune and not sure, for gas i will use a referenz table
this values then must be a referenz that you have to measuring by "live" i think.
but i will read first datasheet to the end :) 

best wishes
rudi ;-)

**Comment by dherrada** [comment]
Closing since this seems more or less resolved
