### ISSUE TITLE
Can't modify the library to work on other i2C buses

### ISSUE THREAD

**Issue by rayan4444** [adafruit/Adafruit_BME680#35]
I am working with a BME680 breakout and trying to use it on an alternative I2C bus on the ATSAMD21G. I've been trying to modify the library to add the option to choose which I2C bus to use the sensor on, without success. Does anyone have advice on how to do it? 

That said, I've had to do these modifications on plenty of libraries because all of them only support the default "Wire" bus. It would be a nice feature to add...

**Comment by ladyada** [comment]
see https://github.com/adafruit/Adafruit_BME680/blob/master/Adafruit_BME680.cpp#L60
