### ISSUE TITLE
  bme.readGas() vs the other one

### ISSUE THREAD

**Issue by Idahowalker** [adafruit/Adafruit_BME680#42]
ESP32, Adruino IDE

bme.readGas(); vs  bme.performReading() / bme.gas_resistance.

I have found that bme.readGas() always returns a gas reading and bme.performReading() / bme.gas_resistance. gives intermittent readings.

**Comment by caternuson** [comment]
They should be notionally equivalent. Can you provide a simple example sketch that demonstrates this.

**Comment by caternuson** [comment]
Closing due to lack of response.
