### ISSUE TITLE
There are BME680 with a new I2C adress of 0x76

### ISSUE THREAD

**Issue by CptHolzschnauz** [adafruit/Adafruit_BME680#46]
If the example sketch can't find a valid sensor, it might be a version with the default adress 0x76.
In this case you have to change the adress on line 35 in Adafruit_BME680.h and everything works fine.
THX Lady Ada & Team for your work!

**Comment by caternuson** [comment]
You can specify a non-default address as a parameter in the call to `begin()`
https://adafruit.github.io/Adafruit_BME680/html/class_adafruit___b_m_e680.html#a902242a4ff4fee842c04243434a4873f

An I2C scan can be used to help confirm the devices address:
https://learn.adafruit.com/scanning-i2c-addresses

**Comment by CptHolzschnauz** [comment]
Perfect! Thank you very much!
