### ISSUE TITLE
Parallel and sequential mods in BME688

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_BME680#47]
Hello,

are there any plans to implement parallel and sequential mods in your library, as it currently only supports force mode?

My best

**Comment by caternuson** [comment]
Which mode are you referring to?
![image](https://user-images.githubusercontent.com/8755041/203636475-810a20c6-fdb9-41d8-89e0-2713fe6d2667.png)

Are you just wanting something non-blocking? See the async example:
https://github.com/adafruit/Adafruit_BME680/blob/master/examples/bme680async/bme680async.ino

**Comment by caternuson** [comment]
Closing due to lack of response. Unclear what the question is asking. Need better explanation of "parallel and sequential mods".
