### ISSUE TITLE
Hidden Datatypes TVOC and eCO2

### ISSUE THREAD

**Issue by jttaylor86** [adafruit/Adafruit_BME680#7]
Hello,

would it be possible to create a library where the hidden datatypes, TVOC and eCO2 are easily readout in a arduino sketch?

Thanks

**Comment by ladyada** [comment]
nope, they're not hidden, they're unimplemented!
see https://github.com/adafruit/Adafruit_BME680/issues/3 
:(

**Comment by jttaylor86** [comment]
Hello there,

they are implemented however I am not smart enough to change the code. Have
a look at hidden_datatypes.h.

Here is a link to an internal release.
https://drive.google.com/drive/folders/1CM039lG9IcAkEAeK6HVUIJseVdomZWKg?usp=sharing

I would be very grateful if you could magic up an Arduino library with TVOC
and CO2 readings as I can't.

Thanks,

Justin

ladyada <notifications@github.com> schrieb am Mo., 26. März 2018, 17:38:

**Comment by ladyada** [comment]
the BSEC/API is under NDA, if you look at the license, we cannot publish/distribute it. so we cannot add that to this library.
