### ISSUE TITLE
Possible error in pressure calculation

### ISSUE THREAD

**Issue by paulcrawford** [adafruit/Adafruit_BME680#9]
In the file Adafruit_BME680.cpp, it appears that the final pressure calculation on line 338 is missing a factor of "/ 100.0". 

The "/ 100.0" is correctly in the previous line 337, but it is in a commented debug print statement so it has no effect on the resultant pressure value.

**Comment by ladyada** [comment]
nope its ok - we return in hPa - the println is mistaken tho :D fixed now!
